blank_issues_enabled: false
contact_links:
  - name: Mandarin Discord
    url: https://discord.com/invite/8xjMHWEuf6
    about: If you are experiencing an issue with Mandarin, and you need tech support, or if you have a general question, try asking in the official Mandarin Discord linked here. Piracy is not allowed.